[package]
name = "uymas"
version = "0.2.0"
authors = ["Conero <conero@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
